clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '


*.elf: $(wildcard D:/EdgeAI/Project4-Person_detection_RT-AK/art-pi-gc0328c-yolo-s/board/linker_scripts/STM32H750XBHx/link.lds)
